---
- hosts: jupyterhub
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-minimal

  vars_prompt:
    - name: "jupyterpw"
      prompt: "Enter a password for the Jupyter user"
      private: yes
      confirm: yes
      encrypt: "sha512_crypt"

  vars:
    nossl: True

  roles:
    - ansible-jupyterhub
